package migrate

import (
	"testing"
)

func TestMigrationLog_AppendAndCount(t *testing.T) {
	log := NewMigrationLog("test-session")
	for i := 0; i < 10; i++ {
		err := log.Append(MigrationLogEntry{Phase: "test", ActionType: "test_action"})
		if err != nil {
			t.Fatalf("Append failed at %d: %v", i, err)
		}
	}
	if log.Count() != 10 {
		t.Errorf("Count: got %d, want 10", log.Count())
	}
}

func TestMigrationLog_SeqNoAutoAssigned(t *testing.T) {
	log := NewMigrationLog("test-session")
	log.Append(MigrationLogEntry{Phase: "parse"})
	log.Append(MigrationLogEntry{Phase: "transform"})

	if log.Entries[0].SeqNo != 1 {
		t.Errorf("First entry SeqNo: got %d, want 1", log.Entries[0].SeqNo)
	}
	if log.Entries[1].SeqNo != 2 {
		t.Errorf("Second entry SeqNo: got %d, want 2", log.Entries[1].SeqNo)
	}
}

func TestMigrationLog_SealPreventsAppend(t *testing.T) {
	log := NewMigrationLog("test-session")
	log.Append(MigrationLogEntry{Phase: "test"})
	log.Seal()

	err := log.Append(MigrationLogEntry{Phase: "test"})
	if err == nil {
		t.Error("expected error when appending to sealed log")
	}
}

func TestMigrationLog_VerifyIntegrity(t *testing.T) {
	log := NewMigrationLog("test-session")
	for i := 0; i < 5; i++ {
		log.Append(MigrationLogEntry{Phase: "test"})
	}
	if err := log.VerifyIntegrity(); err != nil {
		t.Errorf("VerifyIntegrity failed: %v", err)
	}
}

func TestMigrationLog_VerifyIntegrity_DetectsTampering(t *testing.T) {
	log := NewMigrationLog("test-session")
	log.Append(MigrationLogEntry{Phase: "test"})
	log.Append(MigrationLogEntry{Phase: "test"})

	log.mu.Lock()
	log.Entries[1].SeqNo = 999
	log.mu.Unlock()

	err := log.VerifyIntegrity()
	if err == nil {
		t.Error("expected integrity error after tampering")
	}
}

func TestMigrationLog_ChecksumVerification(t *testing.T) {
	log := NewMigrationLog("test-session")
	original := "hello world"
	entry := MigrationLogEntry{
		Phase:          "test",
		Original:       original,
		ChecksumBefore: sha256Sum(original),
	}
	log.Append(entry)

	if err := log.VerifyIntegrity(); err != nil {
		t.Errorf("Checksum verification failed: %v", err)
	}
}

func TestMigrationLog_ChecksumMismatch(t *testing.T) {
	log := NewMigrationLog("test-session")
	entry := MigrationLogEntry{
		Phase:          "test",
		Original:       "hello world",
		ChecksumBefore: "bad_checksum",
	}
	log.Append(entry)

	err := log.VerifyIntegrity()
	if err == nil {
		t.Error("expected checksum mismatch error")
	}
}

func TestMigrationLog_IDAutoGenerated(t *testing.T) {
	log := NewMigrationLog("test-session")
	log.Append(MigrationLogEntry{Phase: "test"})

	if log.Entries[0].ID == "" {
		t.Error("ID should be auto-generated")
	}
}

func TestMigrationLog_TimestampAutoSet(t *testing.T) {
	log := NewMigrationLog("test-session")
	log.Append(MigrationLogEntry{Phase: "test"})

	if log.Entries[0].Timestamp.IsZero() {
		t.Error("Timestamp should be auto-set")
	}
}
