package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
)

// handleExport 导出架构数据
func handleExport(w http.ResponseWriter, r *http.Request) {
	archMu.RLock()
	defer archMu.RUnlock()

	if archData == nil {
		http.Error(w, "no data", http.StatusServiceUnavailable)
		return
	}

	format := r.URL.Query().Get("format")
	if format == "" {
		format = "json"
	}

	w.Header().Set("Access-Control-Allow-Origin", "*")

	switch format {
	case "csv":
		w.Header().Set("Content-Type", "text/csv; charset=utf-8")
		w.Header().Set("Content-Disposition", "attachment; filename=architecture.csv")
		w.Write([]byte("File,Layer,LayerName,Lines,Symbols,Imports,Dependencies,DependedBy\n"))
		for _, f := range archData.Files {
			fmt.Fprintf(w, "%s,%s,%s,%d,%d,%d,%d,%d\n",
				f.Name, f.Layer, f.LayerName, f.Lines, len(f.Symbols),
				len(f.Imports), len(f.DependsOn), len(f.DependedBy))
		}
	case "plantuml":
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.Header().Set("Content-Disposition", "attachment; filename=architecture.puml")
		writePlantUML(w, archData)
	case "dot":
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.Header().Set("Content-Disposition", "attachment; filename=architecture.dot")
		writeDOT(w, archData)
	default:
		w.Header().Set("Content-Type", "application/json; charset=utf-8")
		w.Header().Set("Content-Disposition", "attachment; filename=architecture.json")
		json.NewEncoder(w).Encode(archData)
	}
}

// writePlantUML 生成 PlantUML 格式的架构图。
func writePlantUML(w io.Writer, data *ArchData) {
	fmt.Fprintln(w, "@startuml")
	fmt.Fprintln(w, "' Architecture: Low-Entropy Core v4.0")
	fmt.Fprintln(w, "' Generated by arch-manager")
	fmt.Fprintln(w, "skinparam backgroundColor #0a0a0a")
	fmt.Fprintln(w, "skinparam defaultTextColor #f5f5f7")
	fmt.Fprintln(w, "skinparam arrowColor #48484a")
	fmt.Fprintln(w, "skinparam packageBorderColor #2c2c2e")
	fmt.Fprintln(w, "")

	// 按层级分组
	for _, l := range data.Layers {
		fmt.Fprintf(w, "package \"%s %s\" as %s #%s22 {\n", l.Layer, l.Name, l.Layer, l.Color)
		for _, f := range data.Files {
			if f.Layer == l.Layer {
				fmt.Fprintf(w, "  [%s] as %s\n", f.Name, toID(f.Name))
			}
		}
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
	}

	// 依赖关系
	for _, f := range data.Files {
		for _, d := range f.DependsOn {
			fmt.Fprintf(w, "%s --> %s\n", toID(f.Name), toID(d))
		}
	}
	fmt.Fprintln(w, "@enduml")
}

// writeDOT 生成 Graphviz DOT 格式的架构图。
func writeDOT(w io.Writer, data *ArchData) {
	fmt.Fprintln(w, "// Architecture: Low-Entropy Core v4.0")
	fmt.Fprintln(w, "// Generated by arch-manager")
	fmt.Fprintln(w, "digraph Architecture {")
	fmt.Fprintln(w, "  bgcolor=\"#0a0a0a\";")
	fmt.Fprintln(w, "  fontcolor=\"#f5f5f7\";")
	fmt.Fprintln(w, "  node [style=filled,fontcolor=\"#f5f5f7\",fontname=\"SF Mono\"];")
	fmt.Fprintln(w, "  edge [color=\"#48484a\"];")
	fmt.Fprintln(w, "")

	// 子图：按层级
	for _, l := range data.Layers {
		fmt.Fprintf(w, "  subgraph cluster_%s {\n", l.Layer)
		fmt.Fprintf(w, "    label=\"%s %s\";\n", l.Layer, l.Name)
		fmt.Fprintf(w, "    color=\"%s\";\n", l.Color)
		fmt.Fprintf(w, "    fontcolor=\"#f5f5f7\";\n")
		for _, f := range data.Files {
			if f.Layer == l.Layer {
				fmt.Fprintf(w, "    \"%s\" [fillcolor=\"%s22\"];\n", f.Name, l.Color)
			}
		}
		fmt.Fprintf(w, "  }\n\n")
	}

	// 依赖关系
	for _, f := range data.Files {
		for _, d := range f.DependsOn {
			fmt.Fprintf(w, "  \"%s\" -> \"%s\";\n", f.Name, d)
		}
	}
	fmt.Fprintln(w, "}")
}

// toID 将文件名转换为 PlantUML 安全的标识符。
func toID(name string) string {
	return strings.ReplaceAll(strings.ReplaceAll(name, ".", "_"), "-", "_")
}
